server:
  port: 9090 #服务启动端口
  servlet:
    context-path: ''   #/reggie
    encoding:
      charset: "UTF-8"
      force: true
      enabled: true
spring:
  application: #    应用的名称，可选
    name: reggie_take_out
  datasource: #  数据源配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid: #连接池
      #      driver-class-name: com.mysql.cj.jdbc.Driver #驱动
      driver-class-name: com.mysql.jdbc.Driver #驱动
      url: jdbc:mysql://localhost:3306/reggie?setUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false #数据库
      username: root #账号
      password: 123456 #密码
#  cache:
#    redis:
#      time-to-live: 1800000 #设置redis缓存时间
#  redis:
#    host: 192.168.10.143
#    port: 6379
#  main:
#    allow-circular-references: true


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
  #  mapper-locations: classpath*:mbg/**/*.xml,classpath*:mapper/**/*.xml
  type-aliases-package: com.Luxifel.reggie.mbg.model


reggie:
  path: /usr/local/restaurantOrder/Img/